# Generated by Django 3.0.4 on 2020-05-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivos', '0003_auto_20200506_1645'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivos',
            options={'verbose_name_plural': 'Archivos'},
        ),
        migrations.AlterField(
            model_name='archivos',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='archivos',
            name='tipo',
            field=models.CharField(max_length=100),
        ),
    ]
