# Generated by Django 3.0.4 on 2020-04-14 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('g_eventos', '0002_auto_20200414_1722'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Evento',
        ),
    ]
