# Generated by Django 3.0.4 on 2020-04-17 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('g_eventos', '0005_auto_20200417_1527'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Evento',
        ),
    ]
