# Generated by Django 3.0.4 on 2020-04-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('g_eventos', '0006_delete_evento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30, verbose_name='Tipo')),
                ('fecha_evento', models.DateField(verbose_name='Fecha')),
                ('hora', models.TimeField(verbose_name='Hora')),
                ('lugar', models.CharField(max_length=50, verbose_name='Lugar')),
                ('notas', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-fecha_evento'],
            },
        ),
    ]
