# Generated by Django 3.0.4 on 2020-05-27 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g_banda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandolero',
            name='contrasena',
            field=models.CharField(default=' ', max_length=18, verbose_name='contraseña'),
        ),
    ]
